### PR TITLE
Fix compatibility with google-services:4.3.0

### LINKED ISSUE #95: Problem with Upgrade to com.google.gms:google-services:4.3.0
After upgrade com.google.gms:google-services from 4.2.0 to 4.3.0

i cant build project and receive this message :

ERROR: Could not get unknown property 'config' for object of type com.google.gms.googleservices.GoogleServicesPlugin$GoogleServicesPluginConfig.

when comment this : 
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
error to disappear

@gdeglin 
@leemunroe 
@stewartpark 
@jkasten2 
@coder543

### PR DESCRIPTION
**Pull request by jkasten2**
* Fixed compatibility issue with `com.google.gms:google-services:4.3.0`
* Fixes "ERROR: Could not get unknown property 'config' for object of type com.google.gms.googleservices.GoogleServicesPlugin$GoogleServicesPluginConfig."
* Updated failing integration test for OneSignal version range
* Fixes #95

### CODE REVIEW

File: src/test/groovy/com/onesignal/androidsdk/MainTest.groovy [hunk 1]
```diff
@@ -1028,16 +1065,17 @@ class MainTest extends Specification {
     //       One to this test may cause duplicated or missing classes with either of these
     //       Might need to follow the AndroidX migration guide to fix and re-add support library
     def 'Find min-support for Firebase and GMS - build'() {
-        GradleTestTemplate.buildArgumentSets[GRADLE_OLDEST_VERSION] = [['transformClassesAndResourcesWithProguardForDebug']]
+        GradleTestTemplate.buildArgumentSets[GRADLE_LATEST_VERSION] = [['build']]
         when:
         // Keep as '+' for latest when checking in to this fails when Google changes requirements
```
Comment (mikechoch) [inline src/test/groovy/com/onesignal/androidsdk/MainTest.groovy]: What is this comment in reference to now since you deleted the `gms_version = '+'`

Comment (jkasten2) [reply src/test/groovy/com/onesignal/androidsdk/MainTest.groovy]: Good catch, I'll clean this up
